#!/usr/bin/env bash
# Crée et qualifie les fixtures de référence pour le harness différentiel et les benchmarks.
# Qualification (plan M0) : chaque fixture doit démarrer après
#   `composer install --no-plugins --no-scripts` sur un checkout nu.
set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"
WORK="${VIVACITY_FIXTURES_DIR:-$DIR/work}"
mkdir -p "$WORK"

emit_runtime_stub() { # options par défaut du template de symfony/runtime
  cat > "$1" <<'PHP'
<?php

// autoload_runtime.php @generated by Symfony Runtime

if (true === (require_once __DIR__.'/autoload.php') || empty($_SERVER['SCRIPT_FILENAME'])) {
    return;
}

$app = require $_SERVER['SCRIPT_FILENAME'];

if (!is_object($app)) {
    throw new TypeError(sprintf('Invalid return value: callable object expected, "%s" returned from "%s".', get_debug_type($app), $_SERVER['SCRIPT_FILENAME']));
}

if (is_string($_SERVER['APP_RUNTIME_OPTIONS'] ??= $_ENV['APP_RUNTIME_OPTIONS'] ?? [])) {
    $_SERVER['APP_RUNTIME_OPTIONS'] = json_decode($_SERVER['APP_RUNTIME_OPTIONS'], true, 512, JSON_THROW_ON_ERROR);
}
$_SERVER['APP_RUNTIME'] ??= $_ENV['APP_RUNTIME'] ?? 'Symfony\\Component\\Runtime\\SymfonyRuntime';
$runtime = new $_SERVER['APP_RUNTIME']($_SERVER['APP_RUNTIME_OPTIONS'] += [
  'project_dir' => dirname(__DIR__, 1),
]);

[$app, $args] = $runtime
    ->getResolver($app)
    ->resolve();

$app = $app(...$args);

exit(
    $runtime
        ->getRunner($app)
        ->run()
);
PHP
}

create() { # name create-project-package boot-command...
  local name="$1" pkg="$2"
  shift 2
  if [ -d "$DIR/projects/$name" ]; then
    # Squelette figé (fixtures/projects, composer.lock compris) : déterministe,
    # sans réseau. Le vendor/ existant est conservé pour la qualification.
    mkdir -p "$WORK/$name"
    (cd "$DIR/projects/$name" && tar -cf - .) | (cd "$WORK/$name" && tar -xf -)
    # Un dépôt git à la fixture, sinon Composer remonte jusqu'à celui de
    # vivacity et en prend la version racine : `dev-main` sur main, `0.16.0`
    # sur un tag (HEAD détaché) — et rector-src, qui remplace `rector/rector
    # self.version`, entre alors en conflit avec `rector/rector <2.0`
    # (2026-09-20, bench lancé sur v0.16.0). Même identité fixe que les
    # harnais : la version racine est celle de la fixture, `dev-main`.
    if [ ! -d "$WORK/$name/.git" ]; then
      (cd "$WORK/$name" && git init -q -b main && git add -A >/dev/null && \
        GIT_AUTHOR_NAME=vivacity GIT_AUTHOR_EMAIL=v@v GIT_AUTHOR_DATE="2026-09-10T00:00:00Z" \
        GIT_COMMITTER_NAME=vivacity GIT_COMMITTER_EMAIL=v@v GIT_COMMITTER_DATE="2026-09-10T00:00:00Z" \
        git -c commit.gpgsign=false commit -q -m fixture)
    fi
  elif [ ! -d "$WORK/$name" ]; then
    echo "== create-project $pkg -> $name (sans scripts ni plugins : aucun PHP exécuté)"
    (cd "$WORK" && composer create-project --no-interaction --no-scripts --no-plugins --no-install --quiet "$pkg" "$name")
  fi
  # composer/installers autorisé : le plugin fait partie du contrat (émulé par
  # vivacity), la qualification tourne avec lui.
  local plugin_flag="--no-plugins"
  if jq -e '.config["allow-plugins"]["composer/installers"] == true' "$WORK/$name/composer.json" >/dev/null 2>&1; then
    plugin_flag=""
  fi
  echo "== qualify $name (install $plugin_flag --no-scripts sur checkout nu)"
  rm -rf "$WORK/$name/vendor"
  (cd "$WORK/$name" && composer install --no-interaction $plugin_flag --no-scripts --quiet)
  # Contrat v1 de vivacity : émulation native du plugin symfony/runtime (stub déterministe).
  if jq -e '[.packages[].name] | index("symfony/runtime")' "$WORK/$name/composer.lock" >/dev/null \
     && [ ! -f "$WORK/$name/vendor/autoload_runtime.php" ]; then
    emit_runtime_stub "$WORK/$name/vendor/autoload_runtime.php"
  fi
  (cd "$WORK/$name" && "$@") >/dev/null
  echo "OK $name"
}

create laravel  laravel/laravel          php artisan --version
create symfony  symfony/symfony-demo     php bin/console --version
create sylius   sylius/sylius-standard   php -d memory_limit=1G bin/console --version
# rector-src ne versionne pas de lock : le squelette figé porte celui résolu le
# 2026-09-10 (paquets dev-main avec default-branch, plugins extension-installer).
create rector   rectorphp/rector-src     php vendor/bin/phpstan --version
# WordPress via composer/installers (wpackagist + roots/soil) : le boot doit
# trouver une classe d'un plugin installé HORS vendor/ (web/app/plugins/soil).
create wordpress vivacity/wordpress-fixture php -r 'require "vendor/autoload.php"; exit(class_exists("Roots\\Soil\\Options") ? 0 : 1);'
# Drupal recommended-project : composer/installers + core-composer-scaffold
# (fichiers scaffoldés dans web/, autoload de référence, DrupalInstalled.php).
create drupal   drupal/recommended-project php vendor/bin/dr --version

echo "Fixtures qualifiées : laravel, symfony, sylius, rector, wordpress, drupal"
