//! Templates for the autoload files, transcribed from the heredocs of
//! `AutoloadGenerator` (docs/reference/AutoloadGenerator.php, Composer
//! 2.10.3). PHP heredoc convention: the blank line before the end marker is
//! part of the string (`...}\n\n`), the final newline is not; every block
//! below reproduces those bytes exactly.
//!
//! The exported structures (`var_export`) work on BYTES: class names are not
//! necessarily valid UTF-8.

use crate::pathutil::php_str_bytes;

pub const CLASS_LOADER_PHP: &str = include_str!("../assets/ClassLoader.php");
pub const LICENSE: &str = include_str!("../assets/LICENSE");

/// `getAutoloadFile($vendorPathToTargetDirCode, $suffix)`; the path code to
/// autoload_real.php is already resolved by the caller.
pub fn autoload_php(real_path_code: &str, suffix: &str) -> String {
    format!(
        r#"<?php

// autoload.php @generated by Composer

if (PHP_VERSION_ID < 50600) {{
    if (!headers_sent()) {{
        header('HTTP/1.1 500 Internal Server Error');
    }}
    $err = 'Composer 2.3.0 dropped support for autoloading on PHP <5.6 and you are running '.PHP_VERSION.', please upgrade PHP or use Composer 2.2 LTS via "composer self-update --2.2". Aborting.'.PHP_EOL;
    if (!ini_get('display_errors')) {{
        if (PHP_SAPI === 'cli' || PHP_SAPI === 'phpdbg') {{
            fwrite(STDERR, $err);
        }} elseif (!headers_sent()) {{
            echo $err;
        }}
    }}
    throw new RuntimeException($err);
}}

require_once {real_path_code};

return ComposerAutoloaderInit{suffix}::getLoader();
"#
    )
}

pub struct RealFileOptions<'a> {
    pub suffix: &'a str,
    pub check_platform: bool,
    pub use_include_path: bool,
    pub use_include_files: bool,
    pub class_map_authoritative: bool,
    pub use_global_include_path: bool,
    pub prepend_autoloader: bool,
    pub target_dir_loader: Option<&'a str>,
    /// `setApcu(true, $prefix)`: the prefix written into `setApcuPrefix`
    /// (Composer draws `bin2hex(random_bytes(10))` when none is given).
    pub apcu_prefix: Option<&'a str>,
}

/// `getAutoloadRealFile(...)`.
pub fn autoload_real_php(o: &RealFileOptions<'_>) -> String {
    let suffix = o.suffix;
    let prepend = if o.prepend_autoloader {
        "true"
    } else {
        "false"
    };
    let mut f = format!(
        r#"<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit{suffix}
{{
    private static $loader;

    public static function loadClassLoader($class)
    {{
        if ('Composer\Autoload\ClassLoader' === $class) {{
            require __DIR__ . '/ClassLoader.php';
        }}
    }}

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {{
        if (null !== self::$loader) {{
            return self::$loader;
        }}

"#
    );
    if o.check_platform {
        f.push_str("        require __DIR__ . '/platform_check.php';\n\n");
    }
    f.push_str(&format!(
        "        spl_autoload_register(array('ComposerAutoloaderInit{suffix}', 'loadClassLoader'), true, {prepend});\n        self::$loader = $loader = new \\Composer\\Autoload\\ClassLoader(\\dirname(__DIR__));\n        spl_autoload_unregister(array('ComposerAutoloaderInit{suffix}', 'loadClassLoader'));\n\n"
    ));
    if o.use_include_path {
        f.push_str("        $includePaths = require __DIR__ . '/include_paths.php';\n        $includePaths[] = get_include_path();\n        set_include_path(implode(PATH_SEPARATOR, $includePaths));\n\n");
    }
    f.push_str(&format!(
        "        require __DIR__ . '/autoload_static.php';\n        call_user_func(\\Composer\\Autoload\\ComposerStaticInit{suffix}::getInitializer($loader));\n\n"
    ));
    if o.class_map_authoritative {
        f.push_str("        $loader->setClassMapAuthoritative(true);\n");
    }

    if let Some(prefix) = o.apcu_prefix {
        f.push_str(&format!(
            "        $loader->setApcuPrefix({});\n",
            crate::templates::php_var_export_str(prefix)
        ));
    }
    if o.use_global_include_path {
        f.push_str("        $loader->setUseIncludePath(true);\n");
    }
    if o.target_dir_loader.is_some() {
        f.push_str(&format!(
            "        spl_autoload_register(array('ComposerAutoloaderInit{suffix}', 'autoload'), true, true);\n\n"
        ));
    }
    f.push_str(&format!("        $loader->register({prepend});\n\n"));
    if o.use_include_files {
        f.push_str(&format!(
            "        $filesToLoad = \\Composer\\Autoload\\ComposerStaticInit{suffix}::$files;\n        $requireFile = \\Closure::bind(static function ($fileIdentifier, $file) {{\n            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {{\n                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;\n\n                require $file;\n            }}\n        }}, null, null);\n        foreach ($filesToLoad as $fileIdentifier => $file) {{\n            $requireFile($fileIdentifier, $file);\n        }}\n\n"
        ));
    }
    f.push_str("        return $loader;\n    }\n");
    if let Some(loader) = o.target_dir_loader {
        f.push_str(loader);
    }
    f.push_str("}\n");
    f
}

/// PHP value exportable through `var_export` (strings as bytes).
#[derive(Debug, Clone)]
pub enum PhpVal {
    Int(i64),
    Str(Vec<u8>),
    /// PHP array (integer or string keys), insertion order.
    Arr(Vec<(PhpKey, PhpVal)>),
}

#[derive(Debug, Clone)]
pub enum PhpKey {
    Int(i64),
    Str(Vec<u8>),
}

impl PhpVal {
    pub fn str(s: &str) -> PhpVal {
        PhpVal::Str(s.as_bytes().to_vec())
    }
}

impl PhpKey {
    pub fn str(s: &str) -> PhpKey {
        PhpKey::Str(s.as_bytes().to_vec())
    }
}

/// `var_export($value, true)`: two spaces per level, `key => ` then, for a
/// nested array, a line break and `array (` at the key's indentation.
pub fn var_export(v: &PhpVal, indent: usize) -> Vec<u8> {
    match v {
        PhpVal::Int(i) => i.to_string().into_bytes(),
        PhpVal::Str(s) => php_str_bytes(s),
        PhpVal::Arr(entries) => {
            let pad = vec![b' '; indent];
            let mut out: Vec<u8> = b"array (\n".to_vec();
            for (k, val) in entries {
                out.extend_from_slice(&pad);
                out.extend_from_slice(b"  ");
                match k {
                    PhpKey::Int(i) => out.extend_from_slice(i.to_string().as_bytes()),
                    PhpKey::Str(s) => out.extend_from_slice(&php_str_bytes(s)),
                }
                out.extend_from_slice(b" => ");
                match val {
                    PhpVal::Arr(_) => {
                        out.push(b'\n');
                        out.extend_from_slice(&pad);
                        out.extend_from_slice(b"  ");
                        out.extend_from_slice(&var_export(val, indent + 2));
                    }
                    _ => out.extend_from_slice(&var_export(val, indent + 2)),
                }
                out.extend_from_slice(b",\n");
            }
            out.extend_from_slice(&pad);
            out.push(b')');
            out
        }
    }
}

fn replace_bytes(haystack: &[u8], from: &[u8], to: &[u8]) -> Vec<u8> {
    if from.is_empty() {
        return haystack.to_vec();
    }
    let mut out = Vec::with_capacity(haystack.len());
    let mut i = 0;
    while i < haystack.len() {
        if haystack[i..].starts_with(from) {
            out.extend_from_slice(to);
            i += from.len();
        } else {
            out.push(haystack[i]);
            i += 1;
        }
    }
    out
}

/// One `public static $prop = ...;` of the static file: var_export, absolute
/// prefixes substituted with `__DIR__` expressions, re-indentation (`    ` +
/// twice the original indentation), trailing spaces trimmed.
pub fn static_property(prop: &str, value: &PhpVal, substitutions: &[(String, String)]) -> Vec<u8> {
    let mut exported = var_export(value, 0);
    for (from, to) in substitutions {
        exported = replace_bytes(&exported, from.as_bytes(), to.as_bytes());
    }
    let mut reindented: Vec<u8> = Vec::with_capacity(exported.len() * 2);
    for (i, line) in exported.split(|b| *b == b'\n').enumerate() {
        if i > 0 {
            reindented.push(b'\n');
        }
        let leading = line.iter().take_while(|b| **b == b' ').count();
        let body = &line[leading..];
        let body_trimmed = {
            let end = body.iter().rposition(|b| *b != b' ').map_or(0, |p| p + 1);
            &body[..end]
        };
        if body_trimmed.is_empty() {
            continue;
        }
        reindented.extend_from_slice(b"    ");
        reindented.extend(std::iter::repeat_n(b' ', leading * 2));
        reindented.extend_from_slice(body_trimmed);
    }
    // ltrim
    let start = reindented.iter().position(|b| *b != b' ').unwrap_or(0);
    let mut out = format!("    public static ${prop} = ").into_bytes();
    out.extend_from_slice(&reindented[start..]);
    out.extend_from_slice(b";\n\n");
    out
}

pub fn autoload_static_php(suffix: &str, properties: &[u8], initializer_props: &[&str]) -> Vec<u8> {
    let mut initializer = String::new();
    for prop in initializer_props {
        initializer.push_str(&format!(
            "            $loader->{prop} = ComposerStaticInit{suffix}::${prop};\n"
        ));
    }
    let mut out = format!(
        "<?php\n\n// autoload_static.php @generated by Composer\n\nnamespace Composer\\Autoload;\n\nclass ComposerStaticInit{suffix}\n{{\n"
    )
    .into_bytes();
    out.extend_from_slice(properties);
    out.extend_from_slice(
        format!(
            "    public static function getInitializer(ClassLoader $loader)\n    {{\n        return \\Closure::bind(function () use ($loader) {{\n{initializer}\n        }}, null, ClassLoader::class);\n    }}\n}}\n"
        )
        .as_bytes(),
    );
    out
}

/// `autoload_{namespaces,psr4,classmap,files}.php` and include_paths.php files.
pub fn map_file(
    kind: &str,
    vendor_path_code: &str,
    app_base_dir_code: &str,
    body: &[u8],
) -> Vec<u8> {
    let mut out = format!(
        "<?php\n\n// {kind} @generated by Composer\n\n$vendorDir = {vendor_path_code};\n$baseDir = {app_base_dir_code};\n\nreturn array(\n"
    )
    .into_bytes();
    out.extend_from_slice(body);
    out.extend_from_slice(b");\n");
    out
}

pub struct PlatformCheckParts {
    /// (PHP_VERSION_ID, `>=`/`>` operator, human-readable version) if a bound is set.
    pub php: Option<(i64, &'static str, String)>,
    pub php_64bit: bool,
    /// Pre-formatted `extension_loaded(...)` lines, sorted by name.
    pub extension_lines: Vec<String>,
}

/// `getPlatformCheck`: the content, or None if there is nothing to check.
pub fn platform_check_php(parts: &PlatformCheckParts) -> Option<String> {
    let mut required_php = String::new();
    if let Some((id, op, human)) = &parts.php {
        required_php.push_str(&format!(
            "\nif (!(PHP_VERSION_ID {op} {id})) {{\n    $issues[] = 'Your Composer dependencies require a PHP version \"{op} {human}\". You are running ' . PHP_VERSION . '.';\n}}\n"
        ));
    }
    if parts.php_64bit {
        required_php.push_str(
            "\nif (PHP_INT_SIZE !== 8) {\n    $issues[] = 'Your Composer dependencies require a 64-bit build of PHP.';\n}\n",
        );
    }
    let mut required_ext = String::new();
    if !parts.extension_lines.is_empty() {
        required_ext.push_str("\n$missingExtensions = array();\n");
        for line in &parts.extension_lines {
            required_ext.push_str(line);
        }
        required_ext.push_str("if ($missingExtensions) {\n    $issues[] = 'Your Composer dependencies require the following PHP extensions to be installed: ' . implode(', ', $missingExtensions) . '.';\n}\n");
    }
    if required_php.is_empty() && required_ext.is_empty() {
        return None;
    }
    Some(format!(
        r#"<?php

// platform_check.php @generated by Composer

$issues = array();
{required_php}{required_ext}
if ($issues) {{
    if (!headers_sent()) {{
        header('HTTP/1.1 500 Internal Server Error');
    }}
    if (!ini_get('display_errors')) {{
        if (PHP_SAPI === 'cli' || PHP_SAPI === 'phpdbg') {{
            fwrite(STDERR, 'Composer detected issues in your platform:' . PHP_EOL.PHP_EOL . implode(PHP_EOL, $issues) . PHP_EOL.PHP_EOL);
        }} elseif (!headers_sent()) {{
            echo 'Composer detected issues in your platform:' . PHP_EOL.PHP_EOL . str_replace('You are running '.PHP_VERSION.'.', '', implode(PHP_EOL, $issues)) . PHP_EOL.PHP_EOL;
        }}
    }}
    throw new \RuntimeException(
        'Composer detected issues in your platform: ' . implode(' ', $issues)
    );
}}
"#
    ))
}

/// `var_export($string, true)`: single quotes, `\\` and `'` escaped.
pub fn php_var_export_str(s: &str) -> String {
    format!("'{}'", s.replace('\\', "\\\\").replace('\'', "\\'"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn var_export_matches_php_layout() {
        let v = PhpVal::Arr(vec![
            (
                PhpKey::str("v"),
                PhpVal::Arr(vec![(PhpKey::str("voku\\"), PhpVal::Int(5))]),
            ),
            (PhpKey::Int(0), PhpVal::str("/a")),
        ]);
        assert_eq!(
            String::from_utf8(var_export(&v, 0)).expect("utf8"),
            "array (\n  'v' => \n  array (\n    'voku\\\\' => 5,\n  ),\n  0 => '/a',\n)"
        );
    }

    #[test]
    fn static_property_reindents_and_substitutes() {
        let v = PhpVal::Arr(vec![(
            PhpKey::str("Foo\\"),
            PhpVal::Arr(vec![(PhpKey::Int(0), PhpVal::str("/abs/vendor/foo/src"))]),
        )]);
        let out = static_property(
            "prefixDirsPsr4",
            &v,
            &[(
                " => '/abs/vendor/".into(),
                " => __DIR__ . '/..' . '/".into(),
            )],
        );
        assert_eq!(
            String::from_utf8(out).expect("utf8"),
            "    public static $prefixDirsPsr4 = array (\n        'Foo\\\\' =>\n        array (\n            0 => __DIR__ . '/..' . '/foo/src',\n        ),\n    );\n\n"
        );
    }

    #[test]
    fn platform_check_php_only() {
        let s = platform_check_php(&PlatformCheckParts {
            php: Some((80401, ">=", "8.4.1".into())),
            php_64bit: false,
            extension_lines: vec![],
        })
        .expect("content");
        assert!(s.contains("$issues = array();\n\nif (!(PHP_VERSION_ID >= 80401)) {\n"));
        assert!(s.contains("You are running ' . PHP_VERSION . '.';\n}\n\nif ($issues) {"));
        assert!(platform_check_php(&PlatformCheckParts {
            php: None,
            php_64bit: false,
            extension_lines: vec![]
        })
        .is_none());
    }
}
